version: '3.7'
networks:
  vnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
      - subnet: 173.22.0.0/24
        gateway: 173.22.0.1
volumes:
  mongodb: {}
  shared-data: {}
services:
  mongodb:
    image: mongo
    container_name: open5gs-mongodb
    ports:
    - 27017:27017
    restart: unless-stopped
    volumes:
    - mongodb:/data/db
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      vnet:
        ipv4_address: 173.22.0.2
  open5gs:
    hostname: open5gs
    image: 5g-core
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.open5gs
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    expose:
    - 38412/sctp
    - 80/tcp
    environment:
    - DB_URI=mongodb://mongodb/open5gs
    - WAIT_HOSTS=mongodb:27017
    - UE_COUNT=4
    depends_on:
    - mongodb
    ports:
    - '38412'
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-core.sh
    networks:
      vnet:
        ipv4_address: 173.22.0.4
  webui:
    hostname: webui
    image: ${USER}/open5gs-webui
    build:
      context: .
      dockerfile: Dockerfile.webui
    container_name: open5gs-webui
    depends_on:
    - mongodb
    ports:
    - 3000:3000
    - 9999:9999
    command: tail -f /dev/null
    environment:
    - DB_URI=mongodb://mongodb/open5gs
    - WAIT_HOSTS=mongodb:27017
    networks:
      vnet:
        ipv4_address: 173.22.0.7
  enb-ueransim:
    hostname: 5g-enb
    image: 5g-enb
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.gnb
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-gnb.sh
    depends_on:
    - open5gs
    - mongodb
    networks:
      vnet:
        ipv4_address: 173.22.0.5
  ue-ueransim-1:
    hostname: 5g-ue-1
    image: 5g-ue
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ue
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-ue.sh
    depends_on:
    - enb-ueransim
    networks:
      vnet:
        ipv4_address: 173.22.0.9
  ue-ueransim-2:
    hostname: 5g-ue-2
    image: 5g-ue
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ue
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-ue.sh
    depends_on:
    - enb-ueransim
    networks:
      vnet:
        ipv4_address: 173.22.0.10
  ue-ueransim-3:
    hostname: 5g-ue-3
    image: 5g-ue
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ue
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-ue.sh
    depends_on:
    - enb-ueransim
    networks:
      vnet:
        ipv4_address: 173.22.0.11
  ue-ueransim-4:
    hostname: 5g-ue-4
    image: 5g-ue
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ue
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - shared-data:/shared-data
    command: ./entrypoint-ue.sh
    depends_on:
    - enb-ueransim
    networks:
      vnet:
        ipv4_address: 173.22.0.12
